### ISSUE TITLE
Caching dio download() results does not work

### ISSUE THREAD

**Issue by kbn** [hurshi/dio-http-cache#75] opened 2021-01-13 14:41 UTC
dio.download() override [options.responseType = ResponseType.stream](https://github.com/flutterchina/dio/blob/master/dio/lib/src/entry/dio_for_native.dart#L80), which is not supported by dio-http-cache.

As a consequence, it is impossible to use the dio download() api call with dio-http-cache.

Possibly related to #65.

**Comment by hurshi** [comment] 2021-01-21 01:24
Thanks for your issue. Duplicate of #65

**Closed by hurshi** 2021-01-21 01:24 UTC
Labels: duplicate
